### ISSUE TITLE
结果不正确

### ISSUE THREAD

**Issue by Codgi-123** [YuanGao-NAU/raspi_nextcloud#1]
已经正确运行脚本：
![image](https://user-images.githubusercontent.com/54504858/110637403-5433aa80-81e8-11eb-8085-5690481c01d7.png)
但是打开完之后显示如下：
![image](https://user-images.githubusercontent.com/54504858/110637442-5c8be580-81e8-11eb-907c-06fc41ef43d4.png)

**Comment by YuanGao-NAU** [comment]
这个问题看样子是php文件不能正确执行,只能像文本文件一样打开导致的. 要解决这个问题,你可以百度搜一下phpinfo,放到根目录看下能不能解析,不能的话就是这个问题. 然后排查是不是php没装好,以及和Apache的连接问题. 我看了一下你的系统似乎是ubuntu, 这个脚本其实是给官方系统写的, 官方系统是Debian, 所以有问题也正常, 如果是树莓派跑ubuntu 20.04的话建议看看[这个](https://ee-fans.com/%e6%a0%91%e8%8e%93%e6%b4%be%e4%bd%bf%e7%94%a8%e5%ae%9d%e5%a1%94%e9%9d%a2%e6%9d%bf%e5%ae%89%e8%a3%85lnmp%e7%8e%af%e5%a2%83/)
