### ISSUE TITLE
创建用户时的问题

### ISSUE THREAD

**Issue by qwekk** [YuanGao-NAU/raspi_nextcloud#2]
安装成功，但进入管理页面创建用户时出问题
提示无法写入文件到/var/www/html/nextcloud/data，于是我创建了这个目录

/var/www/html/nextcloud/data 设置权限为777，提示：
错误
您的数据目录可被其他用户读取

请更改权限为 0770 以避免其他用户查看目录。
然而，修改为0770又提示：
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

请问该怎么解决了

**Comment by YuanGao-NAU** [comment]
我也不知道怎么解决，看下/www/html/nextcloud/的所有者是谁吧，然后创建的新文件夹和父文件夹保持一致试试看，还不行的话我就不知道了。话说nextcloud安装好不是有一个用户了吗？

**Comment by qwekk** [comment]
抱歉抱歉，后来发现是我数据存储地址忘改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuan ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuanGao-NAU/raspi_nextcloud] 创建用户时的问题 (#2)





 
我也不知道怎么解决，看下/www/html/nextcloud/的所有者是谁吧，然后创建的新文件夹和父文件夹保持一致试试看，还不行的话我就不知道了。话说nextcloud安装好不是有一个用户了吗？
