### ISSUE TITLE
视频不能在线播放

### ISSUE THREAD

**Issue by qwekk** [YuanGao-NAU/raspi_nextcloud#3]
用了好几个mp4视频测试，结果都不行
<a href="https://imgtu.com/i/6aNCs1"><img src="https://s3.ax1x.com/2021/03/12/6aNCs1.png" alt="6aNCs1.png" border="0" /></a>

**Comment by YuanGao-NAU** [comment]
自己百度解决好吧

**Comment by qwekk** [comment]
这不是百度不到嘛



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuan ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 晚上8:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuanGao-NAU/raspi_nextcloud] 视频不能在线播放 (#3)





 
自己百度解决好吧
